### ISSUE TITLE
Support for older versions of react

### ISSUE THREAD

**Issue by AlexandreOndet** [thewca/wca-components#4]
Hi,
The project I'm working on uses react 17 but the dependencies for wca-components currently force react 18. Is there a legitimate reason for that, for example a feature that would be missing in older versions or could it be possible to add the support of older versions ?

**Comment by FinnIckler** [comment]
Hi Alexandre, 
This project uses React 18 because it was the newest version when we started it. I will look through the code and see if there is a reason to not set the needed version of react lower

**Comment by AlexandreOndet** [comment]
Hi Finn,
Any idea of when you will have the time to look at it ? My project is moving pretty fast so I'm really looking forward to using your event selector!
Thank you very much for your help

**Comment by FinnIckler** [comment]
Sorry, I was at worlds and am still traveling. I will try to get too it by the end of the week!

**Comment by AlexandreOndet** [comment]
Hi Finn,
Any news on your side ? (Sorry if I'm being insistent, It's not my intention)
Thank you for your help!

**Comment by FinnIckler** [comment]
I didn't get to it yet because of the heat here in Tokyo really killing my productivity during the evening. Tomorrow evening I will be in the airport though and have a bunch of time. I will give another update or already write the PR then.

**Comment by FinnIckler** [comment]
I think it should work by setting all react dependencies to `^17.0.0 || ^18.0.0` which seems to be what other libraries (like semantic) do. I need to regenerate the package.lock file, but currently the wifi isn't good enough. But I have two more airports to try in the next 12 hours ;).

**Comment by AlexandreOndet** [comment]
Great news, thank you very much for your help, it's really appreciated!

**Comment by FinnIckler** [comment]
Can you confirm that all the dependencies line up with the versions you are using? Then I will merge

**Comment by AlexandreOndet** [comment]
I confirm, it seems to line up perfectly!

**Comment by FinnIckler** [comment]
I pushed a new release. Please report back if it works once it hits npm in like 5 minutes.

**Comment by AlexandreOndet** [comment]
I installed it successfully the previous error is gone, but it doesn't compile:
Cannot find module '@wca/helpers'
It should probably be in the peer deps I guess.

**Comment by dunkOnIT** [comment]
Hi Alexandre! Finn's doesn't have Github access at the moment, but he asked me to convey the follow: 
> you can make a PR that just adds wca-helpers to the peer dependencies and bumps the version by 0.0.1

I don't have the context here but hopefully that makes sense! Let me know if any further help is required.

**Comment by AlexandreOndet** [comment]
Done
